version: '2'

services:
  angular:
    build: 'angular/'
    restart: always
    container_name: 'mts_angular'
    networks:
      - my-thai-star
    ports:
      - '8080:80'
      - '444:443'
  java:
    build: 'java/'
    restart: always
    container_name: 'mts_java'
    ports:
      - 9090:8080
    networks:
      - my-thai-star

networks:
  my-thai-star:
    driver: bridge